stages:
  - build
  - deploy
  - release_draft
  - release_submit

image: ${CI_DOCKER_REGISTRY}/esp32-ci-env

before_script:
  # Use CI Tools
  #TODO Using _dev now, change it without _dev (see Variables)
  - curl -sSL ${CIT_DEV_LOADER_URL} | sh
  - source citools/import_functions

.add_gh_remote_key: &add_gh_remote_key |
  cit_add_ssh_key "${GH_SSH_KEY}"
  git remote remove gh || true
  git remote add gh ${GH_PUSH_REPO}

.release_tag_filter: &release_tag_filter
  only:
    - /^v[0-9].*$/

.release_submit_action: &release_submit_action
  when: manual
  allow_failure: true

.build:
  stage: build
  tags:
    - build
  variables:
    #CI_DEBUG_TRACE: "true"
  script:
    - set -x
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_SHA
    #- echo $CI_COMMIT_TAG

push_master_to_github:
  stage: deploy
  only:
    - master
  when: on_success
  dependencies: []
  script:
    - *add_gh_remote_key
    - git push --force gh HEAD:master

gh_release_draft:
  stage: release_draft
  <<: *release_tag_filter
  when: on_success
  tags:
    - build
  script:
    - export GITHUB_TOKEN=${GH_TOKEN}
    - export GITHUB_USER=${GH_USER}
    - export GITHUB_REPO=${GH_REPO}
    - cit_gh_tool_init

    # Pushing the tag anyway
    - *add_gh_remote_key
    - git push --force gh ${CI_COMMIT_TAG}

    # Releasing a draft
    - ${CIT_GH_TOOL} delete --tag ${CI_COMMIT_TAG} || true
    - ${CIT_GH_TOOL} release --tag ${CI_COMMIT_TAG} --draft

    # Upload the archive
    - git_gh_tool_upload_file "data.txt"

Release_tag_submit:
  stage: release_submit
  <<: *release_tag_filter
  <<: *release_submit_action
  dependencies: []
  variables:
    GIT_STRATEGY: none
  script:
    - export GITHUB_TOKEN=${GH_TOKEN}
    - export GITHUB_USER=${GH_USER}
    - export GITHUB_REPO=${GH_REPO}
    - cit_gh_tool_init
    - echo "WARNING! The description will be replaced anyway. You have to fix them on GitHub.com/"
    - ${CIT_GH_TOOL} edit --tag ${CI_COMMIT_TAG}

Pre-Release_tag_submit:
  stage: release_submit
  <<: *release_tag_filter
  <<: *release_submit_action
  dependencies: []
  variables:
    GIT_STRATEGY: none
  script:
    - export GITHUB_TOKEN=${GH_TOKEN}
    - export GITHUB_USER=${GH_USER}
    - export GITHUB_REPO=${GH_REPO}
    - cit_gh_tool_init
    - echo "WARNING! The description will be replaced anyway. You have to fix them on GitHub.com/"
    - ${CIT_GH_TOOL} edit --tag ${CI_COMMIT_TAG} --pre-release

Delete_tag_release:
  stage: release_submit
  <<: *release_tag_filter
  <<: *release_submit_action
  dependencies: []
  variables:
    GIT_STRATEGY: none
  script:
    - export GITHUB_TOKEN=${GH_TOKEN}
    - export GITHUB_USER=${GH_USER}
    - export GITHUB_REPO=${GH_REPO}
    - cit_gh_tool_init
    - echo "WARNING! The description will be replaced anyway. You have to fix them on GitHub.com/"
    - ${CIT_GH_TOOL} delete --tag ${CI_COMMIT_TAG} || true
